#include <cstdint>
#include <cstdio>
#include <limits>

// Scan a specific subset of GClk divider values instead of all of 2-255
#define USE_GCLK_DIV_LIST 0

// The frequency of the PLL output is
//
//   Fpll = Fref * (LDR + LDRFRAC/16) * 1 / (PSC)
//
// (The fact that LDR is specified as one less than the desired
//  multiplier and PSC is an exponent of 2 are ignored here and
//  treated as implementation details since they don't affect
//  the math)
//
// PSC can be 1, 2, or 4.  We choose 4, as a higher denominator
// allows higher resolution in the LDR value.  We also treat
// LDR as an integer value that needs to later be divided by
// 16 instead of a whole and fractional part.  This gives:
//
//                 LDR / 16      Fref * LDR
//  Fpll = Fref * ----------  = -------------
//                    4              64
//
// The hardware requires that the output of the PLL be between
// 48Mhz and 96Mhz, so:
//
//             Fref * LDR                 48Mhz * 64              96Mhz * 64
//   48Mhz <= ------------ <= 96Mhz  --> ------------ <= LDR <= -------------
//                 64                        Fref                    Fref    
//
// *** TODO: Update here for TCC mode (F vs F/2)
// The PID waveform is generated by the TCC driven by the PLL clock.
// Since the waveform updates when a TCC count is matched, the period
// time is:
//
//           Fpll
//  Ftcc = --------
//          TCCcnt
//
// Substituting the above values for Fpll, we get:
//
//         Fref * LDR
// Ftcc = -------------
//         64 * TCCcnt
//
// We are controlling the frequency by selecting LDR and TCCcnt, so solve
// for the ratio of those values:
//
//   LDR       Ftcc * 64
// -------- = -------------
//  TCCcnt       Fref
//
// Knowing the range requirements for LDR above, we can calculate a scalar
// to apply to move (Ftcc * 64) into the required range:
//
//                        Ftcc * 64
//  Shift = Floor( log2( ----------- ) )
//                         LDR Min
//
// (This can be done in hardware with CLZ)
//
// Our final values are then:
//
//   LDR    = (Ftcc * 64) >> Shift
//   TCCcnt = (Fref)      >> Shift
//
// For an example, If we want an output frequency of 1.4Mhz:
//   Shift = 15     ( 1.4MHz * 64 / 1536 = 0x0000E3DD, FFS = 15)
//
// LDR = (1.4Mhz * 64) >> 15 = 2734
// TCCcnt = (2Mhz) >> 15 = 61
//
// Plugging these values into the formula above shows that:
//
//                       Fref (2Mhz) * LDR (2734)
// Ftcc (1.400614Mhz) = --------------------------
//                           64 * TCCcnt (61)

// All primes from 2-255, which is about 20% of the size of 2-255.  This rarely
// picks the same values as the full scan, and increases the errors from around
// a thousandth of a percent to a hundredth of a percent. This is fine for our
// needs, but if there's an ideal smaller list to scan, primes don't seem to be it.
#if USE_GCLK_DIV_LIST
uint8_t divValues[] = {
      2,   3,   5,   7,  11,  13,  17,  19,  23,  29,  31,  37,  41,  43,  47,  53,
     59,  61,  67,  71,  73,  79,  83,  89,  97, 101, 103, 107, 109, 113, 127, 131,
    137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223,
    227, 229, 233, 239, 241, 251,
};
#define FOR_DIV_VALUES(var)   for (unsigned var : divValues)
#else
#define FOR_DIV_VALUES(var)   for (unsigned var = 2; var <= 255; ++var)
#endif

struct PllTccConfig {
  uint8_t gclkDiv;
  uint16_t ldr; // Integer value of both LDR parts -> (reg LDR + 1) * 16 + LDRFRAC * 16;
  uint32_t tccCnt;
  int32_t error;

  // Allows functions returning this type to be constexpr
  constexpr PllTccConfig() {}
};

// The GClk used as the reference clock for the PLL is the 48Mhz
// internal osc divided by some prescalar
static const uint32_t OscFreq = 48'000'000;

// The hardware requires the PLL output to be 48Mhz-96Mhz
static const uint32_t PllMinFreq = 48'000'000;

// We choose a 4 as the divisor to allow more resolution in the multiplier
static const uint32_t PllDiv = 4;

// We are calculating LDR as a single integer that needs to be divided by
// 16 to get the real LDR register value and the 4-bit fractional part.
static const uint32_t LdrScalar = 16;

static constexpr unsigned getNextSmallestPowerOf2Shift(uint32_t val) {
  return (sizeof(val) * 8 - 1) - __builtin_clz(val);
}

static constexpr PllTccConfig calcConfigVals(uint32_t freq, uint8_t gclkDiv) {
  PllTccConfig config;

  const uint32_t gclk = (OscFreq / gclkDiv);

  // 48Mhz * 64 is very close to overflowing a 32-bit value (~2^31.5);
  // be careful if either of these parameters changes
  const uint32_t ldrMin = (PllMinFreq * LdrScalar * PllDiv + gclk - 1) / gclk;

  const uint8_t shift = getNextSmallestPowerOf2Shift(freq * LdrScalar * PllDiv / ldrMin);

  config.gclkDiv = gclkDiv;
  config.ldr = (freq * LdrScalar * PllDiv) >> shift;
  config.tccCnt = gclk >> shift;

  // Logically we would calculate PLL frequency as:
  //
  //    const uint32_t pllOut = gclk * config.ldr / PllDiv / LdrScalar;
  //
  // But gclk * ldr can overflow uint32_t by about 1.5x when PllDiv is 4:
  //
  //   ldrMax = PllMaxFreq * LdrScalar * PllDiv / gclk
  //
  //    96Mhz * LdrScalar * PllDiv * GClkDiv       48Mhz      
  //   -------------------------------------- *  ---------
  //                 48Mhz                        GClkDiv     
  //
  //   |----------- LDR Max ----------------|    |- GClk -|
  //
  //                        |  |  |                                                              
  //                        v  v  v                                                              
  //
  //         96 * LdrScalar
  //  Max = ---------------- * PllDiv * 48Mhz ~= 2^32.5
  //              48
  //
  // Divide gclk by PllDiv first to avoid overflow. This makes the max:
  //
  //      32 * 48Mhz ~= 2^30.5
  //
  // (LDR scales with PllDiv, so if PllDiv goes down, LDR will go down too and avoid the overflow)

  const uint32_t pllOut = (gclk / PllDiv) * config.ldr / 16;
  const uint32_t tccOut = pllOut / config.tccCnt;

  config.error = tccOut - freq;

  return config;
}

PllTccConfig constexpr getPllTccConfigForFreq(uint32_t targetFreq) {
  PllTccConfig best;

  uint32_t minError = std::numeric_limits<uint32_t>::max();

  // Scan through the available range of GClk values, calculating the
  // LDR and Tcc values for each and determining the resulting error
  // from the requested frequency.  Return the config with lowest error.
  FOR_DIV_VALUES(gclkDiv) {
    PllTccConfig config = calcConfigVals(targetFreq, gclkDiv);

    uint32_t posError = config.error < 0 ? -config.error : config.error;
    if (posError < minError) {
      minError = posError;
      best = config;
    }
  }

  return best;
}

#if defined (PC_TEST)
// Test function to print out a table of calculated values from 1.00Mhz -> 4.00Mhz,
// our target piece ID range
int main() {
  for (unsigned i = 100; i <= 400; ++i) {
    const uint32_t targetFreq = i * 10000;

    PllTccConfig best = getPllTccConfigForFreq(targetFreq);

    const uint32_t gclk = OscFreq / best.gclkDiv;
    // On PC only, calculate this more accurately (64 bit) instead of doing the PllDiv first
    const uint32_t pll = (uint64_t)gclk * best.ldr / PllDiv / 16;
    const uint32_t tcc = pll / best.tccCnt;
    const float MHZ = 1'000'000;

    printf("%5.03fMHz:  GDiv: %3u  GClk: %6.03fMHz  LDR: %4u  FRAC: %2u  PLL: %6.03fMHz  TccCNT: %4u  Tcc: %5.03fMHz  Error: %+.07f\n",
        targetFreq / MHZ,
        best.gclkDiv,
        gclk / MHZ,
        (best.ldr >> 4) - 1,
        best.ldr & 0x0f,
        pll / MHZ,
        best.tccCnt,
        tcc / MHZ,
        (float)best.error / targetFreq);
  }
}
#endif
