#include <cstdint>
#include <cstdio>
#include <limits>

// Scan a specific subset of GClk divider values instead of all of 2-255
#define USE_GCLK_DIV_LIST 0

// The frequency of the PLL output is
//
//   Fpll = Fgclk * (LDR + LDRFRAC/16) * 1 / (PSC)
//
// (The fact that LDR is specified as one less than the desired
// multiplier and PSC is an exponent of 2 are ignored here and treated
// as implementation details since they don't affect the math)
//
// The prescalar (PSC) is a divisor applied after the LDR
// multiplication which can be 1, 2, or 4.
//
// We will calculate LDR as an integer value that needs to later be
// divided by LdrScalar instead of a whole and fractional part.  This
// gives:
//
//                  LDR / LdrScalar        Fgclk * LDR
//  Fpll = Fgclk * -----------------  = -----------------
//                       PSC             PSC * LdrScalar
//
// The hardware requires that the output of the PLL multiplication
// (i.e. before the PSC is applied) be between 48Mhz and 96Mhz, so:
//
//             Fgclk * LDR
//   48Mhz <= ------------ <= 96Mhz
//             LdrScalar
//
//               |  |  |
//               v  v  v
//
//     48Mhz * LdrScalar              96Mhz * LdrScalar
//   -------------------- <= LDR <= --------------------
//          Fgclk                         Fgclk
//
// (The docs and MCC utility are unclear about whether the 48 - 96
//  range applies before or after the PSC, but testing determined it to
//  be before, as multiplying higher and dividing down into the 48 - 96
//  range outputs no clock at all)
//
// The PID waveform is generated by the TCC driven by the PLL clock.
// Since the waveform updates when a TCC count is matched, the period
// time is:
//
//            Fpll
//   Ftcc = --------
//           TCCcnt
//
// Substituting the above values for Fpll, we get:
//
//                 Fgclk * LDR
//   Ftcc = --------------------------
//           PSC * LdrScalar * TCCcnt
//
// We are controlling the frequency by selecting LDR and TCCcnt, so
// solve for the ratio of those values:
//
//     LDR       Ftcc * PSC * LdrScalar
//   -------- = ------------------------
//    TCCcnt            Fgclk
//
// We will use the numerator as our LDR value and the denominator as
// the TCC count.
//
// Knowing the range requirements for LDR above, we can calculate a
// scalar to apply to adjust LDR (i.e. Ftcc * PSC * LdrScalar) into
// the required range:
//
//                         Ftcc * PSC * LdrScalar
//   Shift = floor( log2( ------------------------ ) )
//                                LDR Min
//
// ( `floor(log2(x))` can be done in hardware with CLZ)
//
// Our final values are then:
//
//   LDR    = (Ftcc * PSC * LdrScalar) >> Shift
//   TCCcnt = (Fgclk                 ) >> Shift
//
// For an example, If we want an output frequency of 1.4Mhz from a
// gclk of 2MHz:
//
//   LDR min = 48Mhz * 16 / 2Mhz = 384
//   Shift = 15     ( 1.4MHz * 1 * 16 / 384 = 0x0000E3DD, FFS = 15)
//
// LDR = (1.4Mhz * 1 * 16) >> 15 = 683
// TCCcnt = (2Mhz) >> 15 = 61
//
// Plugging these values into the formula above shows that:
//
//                        Fgclk (2Mhz) * LDR (683)
// Ftcc (1.399590 Mhz) = --------------------------
//                            16 * TCCcnt (61)
//

#if USE_GCLK_DIV_LIST
// All primes from 24-255, which is about 20% of the size of 24-255.
// (Start at 24 because the maximum PLL input clock frequency is 2MHz
// and 48MHz OSC / 24 = 2MHz.)  This rarely picks the same values as
// the full scan, and increases the errors from around a thousandth of
// a percent to a hundredth of a percent. This is fine for our needs,
// but if there's an ideal smaller list to scan, primes don't seem to
// be it.
uint8_t divValues[] = {
     29,  31,  37,  41,  43,  47,  53,  59,  61,  67,  71,  73,  79,  83,  89,  97,
    101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179,
    181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251,
};
#define FOR_DIV_VALUES(var)   for (unsigned var : divValues)
#else
#define FOR_DIV_VALUES(var)   for (unsigned var = 24; var <= 255; ++var)
#endif

struct PllTccConfig {
  uint8_t gclkDiv;
  uint8_t ldrFrac;
  uint16_t ldrWhole;
  uint32_t tccCnt;
  int32_t error;

  // Allows functions returning this type to be constexpr
  constexpr PllTccConfig() {}
};

// The GClk used as the reference clock for the PLL is the 48Mhz
// internal osc divided by some prescalar
static constexpr uint32_t OscFreq = 48'000'000;

// The hardware requires the output PLL of the PLL multiplication to be 48Mhz-96Mhz
static constexpr uint32_t PllMinFreq = 48'000'000;

// We choose a divider of 1 to allow for higher TCC count values
//  (This is PSC in the math comment above)
static constexpr uint32_t PllDiv = 1;

// We are calculating LDR as a single integer that needs to be divided by
// a scalar to get the whole and fractional parts.
//   - Use 16 to allow use of the FRAC bits
//   - Use 1 to disallow FRAC bits and only calculate whole LDR values
//     with a FRAC of 0.
// The latter may be desirable, since the FRAC may generate jitter in
// the PLL output.
static constexpr uint32_t LdrScalar = 1;

static constexpr unsigned getNextSmallestPowerOf2Shift(uint32_t val) {
  return (sizeof(val) * 8 - 1) - __builtin_clz(val);
}

static constexpr PllTccConfig calcConfigVals(uint32_t targetFreq, uint8_t gclkDiv) {
  PllTccConfig config;

  const uint32_t gclk = (OscFreq / gclkDiv);

  const uint32_t ldrMin = (PllMinFreq * LdrScalar + gclk - 1) / gclk;

  const uint8_t shift = getNextSmallestPowerOf2Shift(targetFreq * LdrScalar * PllDiv / ldrMin);
  const uint32_t ldr = (targetFreq * LdrScalar * PllDiv) >> shift;

  config.gclkDiv = gclkDiv;
  config.ldrWhole = ldr / LdrScalar;
  config.ldrFrac = ldr % LdrScalar;
  config.tccCnt = gclk >> shift;

  const uint32_t pllOut = gclk * ldr / PllDiv / LdrScalar;
  const uint32_t tccOut = pllOut / config.tccCnt;

  config.error = tccOut - targetFreq;

  return config;
}

PllTccConfig constexpr getPllTccConfigForFreq(uint32_t targetFreq) {
  PllTccConfig best;

  uint32_t minError = std::numeric_limits<uint32_t>::max();

  // Scan through the available range of GClk values, calculating the
  // LDR and Tcc values for each and determining the resulting error
  // from the requested frequency.  Return the config with lowest error.
  FOR_DIV_VALUES(gclkDiv) {
    PllTccConfig config = calcConfigVals(targetFreq, gclkDiv);

    uint32_t posError = config.error < 0 ? -config.error : config.error;
    if (posError < minError) {
      minError = posError;
      best = config;
    }
  }

  return best;
}

#if defined (PC_TEST)
// Test function to print out a table of calculated values from 1.00Mhz -> 4.00Mhz,
// our target piece ID range
int main() {
  for (unsigned i = 300; i <= 1000; i += 50) {
    const uint32_t targetFreq = i * 10000;

    PllTccConfig best = getPllTccConfigForFreq(targetFreq);

    const uint32_t gclk = OscFreq / best.gclkDiv;
    // On PC only, calculate this more accurately (64 bit) instead of doing the PllDiv first
    const uint32_t pll = (uint64_t)gclk * (best.ldrWhole * LdrScalar + best.ldrFrac) / PllDiv / LdrScalar;
    const uint32_t tcc = pll / best.tccCnt;
    const float MHZ = 1'000'000;

    printf("%6.03fMHz:  GDiv: %3u  GClk: %6.03fMHz  LDR: %4u  FRAC: %2u  PLL: %6.03fMHz  TccCNT: %4u  Tcc: %5.03fMHz  Error: %+.07f\n",
        targetFreq / MHZ,
        best.gclkDiv,
        gclk / MHZ,
        best.ldrWhole - 1,
        best.ldrFrac,
        pll / MHZ,
        best.tccCnt,
        tcc / MHZ,
        (float)best.error / targetFreq);
  }
}
#endif
