import sys
from math import floor, log2

# The frequency of the PLL output is
#                                                   
#   Fpll = Fref * (LDR + LDRFRAC/16) * 1 / (PSC)   
#                                                   
# (The fact that LDR is specified as one less than the desired
#  multiplier and PSC is an exponent of 2 are ignored here and
#  treated as implementation details since they don't affect
#  the math)
#
# PSC can be 1, 2, or 4.  We choose 4, as a higher denominator
# allows higher resolution in the LDR value.  We also treat
# LDR as an integer value that needs to later be divided by
# 16 instead of a whole and fractional part.  This gives:
#                                                  
#                 LDR / 16      Fref * LDR         
#  Fpll = Fref * ----------  = -------------
#                    4              64             
# 
# We are using a GClk at 2MHz as our reference clock.  The hardware
# requires that the output of the PLL be between 48Mhz and 96Mhz, so:
#                                                  
#             2Mhz * LDR                                                                             
#   48Mhz <= ------------ <= 96Mhz  --> 1536 <= LDR <= 3072                                                  
#                 64                                                                                  
#                                                  
# *** TODO: Update here for TCC mode (F vs F/2)
# The PID waveform is generated by the TCC driven by the PLL clock.
# Since the waveform updates when a TCC count is matched, the period
# time is:
#
#           Fpll
#  Ftcc = --------
#          TCCcnt
#
# Substituting the above values for Fpll, we get:
#
#         Fref * LDR                                
# Ftcc = -------------
#         64 * TCCcnt                              
#
# We are controlling the frequency by selecting LDR and TCCcnt, so solve
# for the ratio of those values:
#
#   LDR       Ftcc * 64                
# -------- = -------------
#  TCCcnt       Fref                   
# 
# Knowing the range requirements for LDR above, we can calculate a scalar
# to apply to move (Ftcc * 64) into the required range:

#                        Ftcc * 64                  
#  Shift = Floor( log2( ----------- ) )
#                          1536                       
#
# (This can be done in hardware with FFS)
#
# Our final values are then:
#
#   LDR    = (Ftcc * 64) >> Shift
#   TCCcnt = (Fref)      >> Shift
#
# For an example, If we want an output frequency of 1.4Mhz:
#   Shift = 15     ( 1.4MHz * 64 / 1536 = 0x0000E3DD, FFS = 15)
# 
# LDR = (1.4Mhz * 64) >> 15 = 2734
# TCCcnt = (2Mhz) >> 15 = 61
#
# Plugging these values into the formula above shows that:
#
#                       Fref (2Mhz) * LDR (2734)
# Ftcc (1.400614Mhz) = --------------------------
#                           64 * TCCcnt (61)

pllDiv=4
tccPsc=1

def calc(freq, gclk):
    ldrMin = int((48000000 * 16 * 4 + gclk - 1) / gclk)
    shift = int(log2((freq*16 * 4)/ldrMin))
    ldr = int(freq * 16 * 4) >> shift
    tccCnt = int(gclk) >> shift

    return (ldrMin, shift, ldr, tccCnt)

class Best:
    pass

for f in sys.argv[1:]:
    tFreq = float(f) * 1000000
    minError = 1.0
    best = Best()

    for gDiv in range(2,256):

        gclk = 48000000 / gDiv
        ldrMin, shift, ldr, tccCnt = calc(tFreq, gclk)

        LDR=int(ldr / 16)-1
        FRAC=ldr % 16

        pllOut=int(int(gclk / pllDiv) * ldr / 16)
        tccOut=int(pllOut / tccPsc / tccCnt)
        error=float(tccOut) / tFreq - 1.0

        #print("   {:3}  gc {:8} lm {:5}  s {:2}  l {:5}  p {:8}  t {:7}  e {:.04f}".format(gDiv, int(gclk), ldrMin, shift, ldr, pllOut, tccOut, error))
        posError = error if error >= 0 else -error
        if posError < minError:
            minError = posError
            best.tFreq = tFreq
            best.gdiv = gDiv
            best.gclk = gclk
            best.LDR = LDR
            best.FRAC = FRAC
            best.pllOut = pllOut
            best.tccCnt = tccCnt
            best.tccOut = tccOut
            best.error = error
        
    print("{:.03f}MHz:  GDiv: {:3}  GClk: {:5.03f}MHz  LDR: {:4}  FRAC: {:2}  PLL: {:2.03f}MHz  TccCNT: {:4}  Tcc: {:2.03f}MHz  Error: {:+.04f}".format(best.tFreq / 1000000.0, best.gdiv, best.gclk / 1000000, best.LDR, best.FRAC, best.pllOut/1000000, best.tccCnt, best.tccOut/1000000, best.error))
